apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend-user

  template:
    metadata:
      labels:
        app: backend-user

    spec:
      containers:
      - name: backend-user

        image: niranjancjoshi/udagram-api-user
        
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: env-config

        - secretRef:
            name: env-secret