apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend-user

  template:
    metadata:
      labels:
        app: backend-user

    spec:
      containers:
      - name: backend-user

        image: niranjancjoshi/udagram-api-user

        ports:
        - containerPort: 8080

        envFrom:
        - configMapRef:
            name: env-config

        - secretRef:
            name: env-secret